# Best reference ever about Shell colors:
# http://askubuntu.com/a/558422

# Foreground color definitions
COLOR_DEFAULT=00
COLOR_BLACK=30
COLOR_RED=31
COLOR_GREEN=32
COLOR_YELLOW=33
COLOR_BLUE=34
COLOR_MAGENTA=35
COLOR_CYAN=36
COLOR_WHITE=37

# Background color definitions
BG_DEFAULT=49
BG_BLACK=40
BG_RED=41
BG_GREEN=42
BG_YELLOW=43
BG_BLUE=44
BG_MAGENTA=45
BG_CYAN=46

# Elements colors
COLOR_HEADER=$COLOR_BLUE